export default [
  {
    id: 4,
    dates: '2014',
    image: 'img/media/rosa-these-storms.jpg',
    link: {
      production: 'http://livingonone.org/rosa/',
      repository: null,
    },
    role: 'Camera Operator',
    summary: '"Rosa, a young Mayan woman, sits alone. She stares directly into the camera and for the first time has the courage to share her story. She has wrestled with rejection, forgiveness and the fight to keep her child alive. Now 27, she must overcome her past to follow the dreams she once thought impossible."',
    tags: 'Cinematography, Photography',
    title: 'Rosa - These Storms',
    type: 'media',
  },
  {
    id: 3,
    dates: '2013',
    image: 'img/media/whole-planet.png',
    link: {
      production: 'https://www.youtube.com/watch?v=HI_bLthLIXs',
      repository: null,
    },
    role: 'Videographer',
    summary: 'Alleviating Poverty in Vietnam is a short promotional video that explores a day in the life Whole Planet Foundation\'s Field Director, Daniel Zoltani, as he visits one of their partners in Vietnam. Daniel visits Tao Yeu Mai (TYM), the leading microfinance institution in Thai Nguyen Province of Northern Vietnam, and goes out with TYM staff to meet with their clients.',
    tags: 'Cinematography, Photography, Audio Recording, Video Editing',
    title: 'Alleviating Poverty in Vietnam',
    type: 'media',
  },
  {
    id: 2,
    dates: '2010',
    image: 'img/media/living-on-one.jpg',
    link: {
      production: 'http://livingonone.org/livingonone/',
      repository: null,
    },
    role: 'Co-Producer, Cinematographer, Assistant Editor',
    summary: '"Living on One Dollar follows the experience of four young friends as they live on less than $1 a day for two months in rural Guatemala. They battle hunger, parasites and the realization that there are no easy answers. Yet, the generosity and strength of Rosa, a 20-year-old woman with her husband Anthony, and Chino, a 12-year-old boy gives them hope that there are effective ways to make a difference."',
    tags: 'Cinematography, Photography, Audio Recording, Video Editing',
    title: 'Living on One Dollar',
    type: 'media',
  },
  {
    id: 1,
    dates: '2010',
    image: 'img/media/aspectator.jpg',
    link: {
      production: 'https://vimeo.com/17481141',
      repository: null,
    },
    role: 'Co-Producer, Cinematographer',
    summary: '"The subject of a psychology study begins to lose his identity when he decides to follow a woman whose presence deteriorates his sight while also invigorating his desire to rediscover himself."',
    tags: 'Production, Cinematography',
    title: 'Aspectator',
    type: 'media',
  },
]
