export default [
  {
    id: 9,
    dates: '2017',
    image: 'img/software/horizonapp.png',
    link: {
      production: 'https://horizonapp.co',
      repository: null,
    },
    role: 'Full Stack Engineer',
    summary: 'Horizon App is an application that uses groups and mutual friends to help users find people and places to stay. I started working on Horizon App as a volunteer Frontend Engineer fixing bugs and rebuilding the web application. I later came back and worked on Horizon as a Full Stack Engineer, adding features, reorganizing and rebuilding the latest API and web application, implementing Redux, Webpack, PostCSS, installing background jobs using Redis, and building mailers and templates for email notifications.',
    tags: 'React, Redux, Webpack, PostCSS, LESS, Ruby, Rails, PostgreSQL, Redis',
    title: 'Horizon App',
    type: 'software',
  },
  {
    id: 8,
    dates: '2017',
    image: 'img/software/ushahidi.png',
    link: {
      production: 'https://ushahidi.com',
      repository: 'https://github.com/ushahidi',
    },
    role: 'Volunteer Developer',
    summary: 'Ushahidi is a non-profit organization based in Nairobi, Kenya that builds software with a social purpose. I contrbitued to one of their open source projects also called Ushahidi - a crowdsourcing application that makes it easy to collect and visualize data on a map. The application has been used for a variety of purposes from relief efforts during a natural disaster to election monitoring.',
    tags: 'AngularJS, CSS, Leaflet, PHP',
    title: 'Ushahidi',
    type: 'software',
  },
  {
    id: 7,
    dates: '2017',
    image: 'img/software/joglonorthwest.png',
    link: {
      production: 'https://joglonorthwest.com',
      repository: null,
    },
    role: 'Freelance Developer',
    summary: 'Joglo Northwest is a family owned business. I built my first website for Joglo several years ago using PHP and MySQL. I rebuilt the website in Javascript to accomadate for new ideas and simplify how content is managed and updated. I built the new site using the latest technologies and simple-cms.',
    tags: 'React, Redux, Webpack, PostCSS, SCSS, Node, Express, MongoDB',
    title: 'Joglo Northwest',
    type: 'software',
  },
  {
    id: 6,
    dates: '2017',
    image: 'img/software/simple-cms.png',
    link: {
      production: 'https://ryanchristo.com/simple-cms/',
      repository: 'https://github.com/ryanchristo/simple-cms',
    },
    role: 'Web Developer',
    summary: 'I started building simple-cms after completing a significant number of the projects in the freeCodeCamp curriculum. The goal of the project was to create a reusable foundation for small business websites and to get practice working on a larger application with React, Redux, Express and MongoDB.',
    tags: 'React, Redux, Webpack, PostCSS, SCSS, Node, Express, MongoDB',
    title: 'simple-cms',
    type: 'software',
  },
  {
    id: 5,
    dates: '2017',
    image: 'img/software/fcc-projects.png',
    link: {
      production: 'https://ryanchristo.com/fcc-projects/',
      repository: 'https://github.com/ryanchristo/fcc-projects',
    },
    role: 'Web Developer',
    summary: 'After completing a Javascript workshop, I continued learning with freeCodeCamp. The curriculum focuses on full stack Javascript development with React, Node, Express and MongoDB.',
    tags: 'React, Redux, Webpack, PostCSS, SCSS, Node, Express, MongoDB',
    title: 'fcc-projects',
    type: 'software',
  },
]
