export default [
  {
    id: 9,
    dates: '2017',
    image: 'img/software/horizonapp.png',
    link: {
      production: 'https://horizonapp.co',
      repository: null,
    },
    role: 'Full Stack Engineer',
    summary: 'Horizon is an application that uses groups and mutual friends to help users find people and places to stay. I started working on Horizon in April as a Frontend Engineer and later filled the role of a Full Stack Engineer. I improved efficiency, maintainability and testability by implementing React best practices and building out a Flux architecture. I rebuilt the web application and wrote the latest api version.',
    tags: 'React, Redux, Webpack, PostCSS, LESS, Ruby, Rails, PostgreSQL, Redis',
    title: 'Horizon App',
    type: 'software',
  },
  {
    id: 8,
    dates: '2017',
    image: 'img/software/ushahidi.png',
    link: {
      production: 'https://ushahidi.com',
      repository: 'https://github.com/ushahidi',
    },
    role: 'Open Source Contributor',
    summary: 'Ushahidi is a non-profit organization based in Nairobi, Kenya that builds software with a social purpose. I recently started contributing to one of their open source projects also called Ushahidi, which is a crowdsourcing application that makes it easy to collect and visualize data on a map. The application has been used for a variety of purposes from relief efforts during a natural disaster to election monitoring.',
    tags: 'AngularJS, CSS, Leaflet, PHP',
    title: 'Ushahidi',
    type: 'software',
  },
  {
    id: 7,
    dates: '2017',
    image: 'img/software/joglonorthwest.png',
    link: {
      production: 'https://joglonorthwest.com',
      repository: null,
    },
    role: 'Freelance Developer',
    summary: 'Joglo Northwest is a family owned business that sells Indonesian art, furniture and stone. I built my first dynamic website for Joglo several years ago using PHP and MySQL and this year I decided to rebuild the website to accomadate for new ideas and to simplify how content is managed and updated. I built the new site using the latest Javascript technologies and my very own simple-cms as the foundation.',
    tags: 'React, Redux, Webpack, PostCSS, SCSS, Node, Express, MongoDB',
    title: 'Joglo Northwest',
    type: 'software',
  },
  {
    id: 6,
    dates: '2017',
    image: 'img/software/simple-cms.png',
    link: {
      production: 'https://ryanchristo.com/simple-cms/',
      repository: 'https://github.com/ryanchristo/simple-cms',
    },
    role: 'Web Developer',
    summary: 'I started building simple-cms after completing the exercises and the majority of the projects in the freeCodeCamp curriculum. The goal of the project was to create a reusable foundation for small business websites and to get practice working on a larger application with React, Redux, Express and MongoDB.',
    tags: 'React, Redux, Webpack, PostCSS, SCSS, Node, Express, MongoDB',
    title: 'simple-cms',
    type: 'software',
  },
  {
    id: 5,
    dates: '2017',
    image: 'img/software/fcc-projects.png',
    link: {
      production: 'https://ryanchristo.com/fcc-projects/',
      repository: 'https://github.com/ryanchristo/fcc-projects',
    },
    role: 'Web Developer',
    summary: 'After completing an introductory workshop in Javascript, I used freeCodeCamp to continue advancing my skills using the latest web development tools and technologies. I completed the exercises and the majority of the projects. I created fcc-projects as a simple landing page that points to the individual projects. The curriculum focuses on full stack Javascript development with React, Node, Express and MongoDB.',
    tags: 'React, Redux, Webpack, PostCSS, SCSS, Node, Express, MongoDB',
    title: 'fcc-projects',
    type: 'software',
  },
]
